[package]
name = "g13"
version = "0.1.0"
authors = ["setup"]
edition = "2018"

[dependencies]
libusb = "0.3"
log = "0.4.3"
simple_logger = "1.0"
uinput = "0.1.3"
failure = "0.1"

serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
clap = "2.32"

